let express=require("express")
const postReq = require("../CONTROLLERS/postReq")
const getReq =require("../CONTROLLERS/getReq")
const getReqById = require("../CONTROLLERS/getreqById")
const deletReq = require("../CONTROLLERS/deleteRq")
const putReq = require("../CONTROLLERS/putREq")
const patchReq = require("../CONTROLLERS/patchReq")
const register = require("../CONTROLLERS/register")
const login = require("../CONTROLLERS/login")
const authentication = require("../MIDDLEWARES/authentication")
const Auth = require("../CONTROLLERS/Auth")
let rout=express.Router()
rout.post("/add", authentication, postReq)
rout.get("/getdata",getReq)
rout.get("/getbyid/:id",getReqById)
rout.delete("/delete/:id",deletReq)
rout.put("/update/:id",authentication, putReq)
rout.patch("/patch/:id",patchReq)
rout.post("/register", register)
rout.post("/login",login)
module.exports=rout